baseurl = "https://www.example.com"
languageCode = 'ko-kor'
title = "Soeun's Dots"
theme = 'hugo-theme-stack'
googleAnalytics = "G-S3NXZWQ2D5"
[permalinks]
  posts = "/:slug/"

# params
[params]
  author = "Soeun Uhm"
  github = "https://github.com/ddoddii"
  og_image = "/assets/img/avatar.png"
  sitename = "Soeun's Dots"
  math = true

  [params.footer]
    since = 2023

  [params.dateFormat]
    published = 'Jan 02, 2006'
    lastUpdated = 'Jan 02, 2006'

  [params.article]
    math = true
    toc = true

  [params.sidebar]
    subtitle = "Changing myself"

  [params.widgets]

    [[params.widgets.homepage]]
    type = "categories"
    limit = 10

    [[params.widgets.homepage]]
    type = "archives"
    limit = 10

    [[params.widgets.page]]
    type = "toc"


  
 
# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# code
pygmentsCodeFences = false
pygmentsUseClasses = false
[markup]
    [markup.highlight]
        codeFences = true
        lineNoStart = 1
        lineNos = true
        tabWidth = 4
        style = "catppuccin-frappe"

[markup.goldmark.renderer]
  unsafe = true

features = [
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]

disableKinds = ["sitemap", "RSS", "robotsTXT"]


    
    

    

