baseURL = 'https://ddoddii.github.io'
languageCode = 'ko-kor'
title = "Soeun's Dots"
theme = 'hugo-theme-stack'
googleAnalytics = "G-S3NXZWQ2D5"

# params
[params]
  author = "Soeun Uhm"
  github = "https://github.com/ddoddii"
  facebook = "https://facebook.com/praveenjuge"
  og_image = "/assets/img/avatar.png"
  sitename = "Soeun's Dots"
 
# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# code
pygmentsCodeFences = false
pygmentsUseClasses = false
[markup]
    [markup.highlight]
        codeFences = true
        lineNoStart = 1
        lineNos = false
        tabWidth = 4
        style = "monokailight"

[markup.goldmark.renderer]
  unsafe = true

features = [
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]

[[params.widgets.page]]
type = "toc"

[params.widgets]

    [[params.widgets.homepage]]
    type = "categories"
    limit = 10

    [[params.widgets.homepage]]
    type = "archives"
    limit = 10

