baseURL = 'https://ddoddii.github.io'
languageCode = 'en-us'
title = "Soeun's Dots"
theme = 'hugo-theme-stack'

# robots.txt
enableRobotsTXT = true

# sitemap 생성
[sitemap]
# always, hourly daily, weekly, monthly, yearly, never
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

# code
pygmentsCodeFences = true
pygmentsUseClasses = true
[markup]
    [markup.highlight]
        lineNoStart = 1
        lineNos = true
        tabWidth = 4

[markup.goldmark.renderer]
  unsafe = true

features = [
    "photoswipe",
    "opengraph",
    "widgets",
    "darkmode",
    "table of contents",
    "search",
]